[general]
import = ["~/.config/alacritty/themes/themes/nordfox.toml"]

[keyboard]
[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

# [colors.bright]
# black = "#414868"
# blue = "#7aa2f7"
# cyan = "#7dcfff"
# green = "#9ece6a"
# magenta = "#bb9af7"
# red = "#f7768e"
# white = "#c0caf5"
# yellow = "#e0af68"
#
# [colors.normal]
# black = "#15161E"
# blue = "#7aa2f7"
# cyan = "#7dcfff"
# green = "#9ece6a"
# magenta = "#bb9af7"
# red = "#f7768e"
# white = "#a9b1d6"
# yellow = "#e0af68"
#
# [colors.primary]
# background = "#1a1b26"
# foreground = "#c0caf5"

[cursor]
blink_interval = 750

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0

[window.padding]
x = 5
y = 3
